// One channel's controller for tb_memch as on the card: LiteDRAM's own controller (otpu_ldc_ch,
// generated by tools/litedram/gen_ldc.py with the production core's settings: bank machines,
// multiplexer, refresher, the crossbar with its two user ports, the ECC frontends, behind a DFI
// stub PHY with WL7DDRPHY's latencies) with otpu_ldn_model's ports, so tb_memch (LDC = 1) runs
// otpu_mem_ch against the real port protocol: when cmd ready rises, when the crossbar asks for a
// write's data (wdata ready, taken without looking at valid), when and on which port the read
// data comes (the user port's write data goes through the ECC frontend's one-beat register, a
// valid / ready handshake). The controller times every command; the data lives here and moves as in
// otpu_ldc_mem: per port in the controller's command order, a write landing once the controller
// has taken its data, a read returning the memory as it is after every earlier command of its
// port, one cycle after the controller returns it, on both ports' data (one read bus). Errors (the
// simulation stops): read data with no read at the head of its port, the controller's two read
// buses differing, a partial write (the ECC port rejects them; otpu_mem_ch merges partial beats
// itself).
module otpu_ldc_model #(
  parameter int BEATS = 1 << 12,
  parameter int CH    = 0
) (
  input  logic              clk,
  input  logic              rst,
  input  logic [1:0]        c_cmd_valid,
  output logic [1:0]        c_cmd_ready,
  input  logic [1:0]        c_cmd_we,
  input  logic [1:0][24:0]  c_cmd_addr,
  input  logic [1:0]        c_wdata_valid,
  output logic [1:0]        c_wdata_ready,
  input  logic [1:0][511:0] c_wdata_data,
  input  logic [1:0][63:0]  c_wdata_we,
  output logic [1:0]        c_rdata_valid,
  output logic [1:0][511:0] c_rdata_data,
  input  logic              dump
);
  logic [511:0] mem [BEATS];
  logic [1:0]        lrv, rv;
  logic [1:0][511:0] lrd, rdp;
  longint n_rd = 0, n_wr = 0, n_miss = 0;
  typedef struct { logic we; logic [24:0] m; } oc_t;

  otpu_ldc_ch u_ctl (
    .sys_clk(clk), .sys_rst(rst),
    .p0_cmd_valid(c_cmd_valid[0]), .p0_cmd_ready(c_cmd_ready[0]), .p0_cmd_we(c_cmd_we[0]),
    .p0_cmd_addr(c_cmd_addr[0]),
    .p0_wdata_valid(c_wdata_valid[0]), .p0_wdata_ready(c_wdata_ready[0]),
    .p0_wdata_data(c_wdata_data[0]), .p0_wdata_we(c_wdata_we[0]),
    .p0_rdata_valid(lrv[0]), .p0_rdata_ready(1'b1), .p0_rdata_data(lrd[0]),
    .p1_cmd_valid(c_cmd_valid[1]), .p1_cmd_ready(c_cmd_ready[1]), .p1_cmd_we(c_cmd_we[1]),
    .p1_cmd_addr(c_cmd_addr[1]),
    .p1_wdata_valid(c_wdata_valid[1]), .p1_wdata_ready(c_wdata_ready[1]),
    .p1_wdata_data(c_wdata_data[1]), .p1_wdata_we(c_wdata_we[1]),
    .p1_rdata_valid(lrv[1]), .p1_rdata_ready(1'b1), .p1_rdata_data(lrd[1]));

  assign c_rdata_valid = rv;
  assign c_rdata_data[0] = rv[1] ? rdp[1] : rdp[0];
  assign c_rdata_data[1] = c_rdata_data[0];
  always @(posedge clk)
    if (!rst && lrd[0] != lrd[1])
      $fatal(1, "otpu_ldc_model ch%0d: the controller's two read buses differ", CH);

  for (genvar p = 0; p < 2; p++) begin : g_port
    oc_t          oq [$];                // commands the controller took, not yet done
    logic [511:0] qd [$];                // write data it took, not yet landed
    always @(posedge clk) begin
      if (rst) begin
        oq.delete(); qd.delete();
        rv[p] <= 1'b0;
      end else begin
        if (c_cmd_valid[p] && c_cmd_ready[p]) oq.push_back('{c_cmd_we[p], c_cmd_addr[p]});
        if (c_wdata_valid[p] && c_wdata_ready[p]) begin   // the ECC frontend's register takes it
          if (c_wdata_we[p] != '1)
            $fatal(1, "otpu_ldc_model ch%0d port %0d: a partial write (we %h)", CH, p, c_wdata_we[p]);
          qd.push_back(c_wdata_data[p]);
        end
        while (oq.size() != 0 && oq[0].we && qd.size() != 0) begin
          mem[int'(oq[0].m) % BEATS] = qd[0];
          void'(oq.pop_front()); void'(qd.pop_front());
        end
        rv[p] <= 1'b0;
        if (lrv[p]) begin
          if (oq.size() == 0 || oq[0].we)
            $fatal(1, "otpu_ldc_model ch%0d port %0d: read data with no read at the head", CH, p);
          rdp[p] <= mem[int'(oq[0].m) % BEATS];
          rv[p] <= 1'b1;
          void'(oq.pop_front());
        end
      end
    end
  end

  int pbr [2] = '{-1, -1};
  always @(posedge clk) if (!rst)
    for (int p = 0; p < 2; p++)
      if (c_cmd_valid[p] && c_cmd_ready[p]) begin
        if (int'(c_cmd_addr[p] >> 7) != pbr[p]) n_miss++;
        pbr[p] = int'(c_cmd_addr[p] >> 7);
        if (c_cmd_we[p]) n_wr++; else n_rd++;
      end
  initial for (int i = 0; i < BEATS; i++) mem[i] = '0;
  always @(posedge clk) if (dump) $display("LDC ch%0d rd=%0d wr=%0d row_miss=%0d", CH, n_rd, n_wr, n_miss);
endmodule
