// Simulation model of the board memory behind the two channels' native ports n_*, as on the card
// (otpu_top AXI = 2): per channel the board's bridge otpu_mem_ch (clock crossing, read-modify-
// write of partial beats, the split onto the two ports) in front of LiteDRAM's own controller
// (otpu_ldc_ch: bank machines, multiplexer, refresher, the crossbar with the two user ports and
// the idle BIST port, the ECC frontends with one read decoder for both ports; generated by
// tools/litedram/gen_ldc.py with the production core's settings, behind a DFI stub PHY with
// WL7DDRPHY's latencies), in the controller clock. The controller times every command; the data
// lives here, one logical image as otpu_native_mem holds it (the same parameters, ports, files and
// address map), and moves in each port's command order (a beat is always on the same port): a
// write lands once the controller has taken its data, a read returns the memory as it is after
// every earlier command of its port, when the controller returns it.
//
// Clocks: the core clock is the caller's (period 10 time units). The controller clock's period is
// 10 * +ldc_ratio=PPM / 1e6 units (PPM: core MHz / controller MHz * 1e6; default 1e6, the core at
// the controller's clock; rtlsim.ldc_plusargs), its edges on the nearest unit. The bridges' XDMA
// side is idle. The dump prints each channel's controller reads and writes and its row changes
// (MEM ch<c> rd=<n> wr=<n> row_miss=<row changes> rmw=0).
module otpu_ldc_mem #(
  parameter int WORDS = 1 << 18,
  parameter int PHYS  = 0,
  parameter int SID   = 0,
  parameter bit CHASH = 1'b1
) (
  input  logic                  clk,
  input  logic                  rst,
  input  logic [1:0]            n_cvalid,
  output logic [1:0]            n_cready,
  input  logic [1:0]            n_cwe,
  input  logic [1:0][24:0]      n_caddr,
  input  logic [1:0]            n_wvalid,
  output logic [1:0]            n_wready,
  input  logic [1:0][511:0]     n_wdata,
  input  logic [1:0][63:0]      n_wmask,
  output logic [1:0]            n_rvalid,
  output logic [1:0][511:0]     n_rdata,
  output logic [1:0][15:0]      n_wdone,
  input  logic                  dump
);
  // the image's words, as otpu_native_mem: word i is mem_lo[i] below H, else mem_hi[i - H]
  localparam int H = WORDS / 2;
  logic [31:0] mem_lo [H];
  logic [31:0] mem_hi [WORDS - H];
  function automatic logic [31:0] rdw(input int i);
    return i < H ? mem_lo[i] : mem_hi[i - H];
  endfunction
  task automatic wrw(input int i, input logic [31:0] v);
    if (i < H) mem_lo[i] = v;
    else mem_hi[i - H] = v;
  endtask
  // the logical beat of channel c's beat m (otpu_native_dram's map)
  function automatic int lbeat(input logic [31:0] m, input int c);
    return int'(m * 2 + (c[0] ^ (CHASH && ^m)));
  endfunction

  // clocks
  logic uclk = 1'b0, xclk = 1'b0;
  longint ratio = 1000000;
  // edge k at 5 * k * ratio units, one unit late and never on a multiple of 5: no controller edge
  // shares a time step with a core clock edge
  function automatic longint uedge(input longint k);
    longint t;
    t = (k * 5 * ratio + 500000) / 1000000 + 1;
    return (t % 5 == 0) ? t + 1 : t;
  endfunction
  initial begin
    longint k;
    k = 1;
    void'($value$plusargs("ldc_ratio=%d", ratio));
    #(uedge(1));
    forever begin
      uclk = ~uclk;
      #(uedge(k + 1) - uedge(k));
      k++;
    end
  end
  always #4 xclk = ~xclk;
  logic xrst = 1'b1, xr1 = 1'b1;
  always @(posedge xclk) {xrst, xr1} <= {xr1, rst};

  longint n_rd [2], n_wr [2], n_miss [2];
  typedef struct { logic we; logic [24:0] m; } oc_t;
  // the ports stay closed for the first 256 core cycles after rst, past the bridges' reset holds
  // (on the card the core waits for calibration)
  int upc = 0;
  logic up;
  always @(posedge clk) upc <= rst ? 0 : (upc < 256 ? upc + 1 : upc);
  assign up = upc == 256;

  for (genvar c = 0; c < 2; c++) begin : g_ch
    logic         urst = 1'b1, ur1 = 1'b1;
    logic [1:0]   cv, cr, cwe, wv, wr, rv, lrv;       // the channel's two ports
    logic [1:0][24:0]  ca;
    logic [1:0][511:0] wd, rd, rdp, lrd;
    logic [1:0][63:0]  we;
    logic         bcr, bwr, brv;
    always @(posedge uclk) {urst, ur1} <= {ur1, rst};
    assign n_cready[c] = up && bcr;
    assign n_wready[c] = up && bwr;
    assign n_rvalid[c] = up && brv;
    otpu_mem_ch #(.XIDW(4)) u_ch (
      .clk, .rst,
      .n_cvalid(up && n_cvalid[c]), .n_cready(bcr), .n_cwe(n_cwe[c]), .n_caddr(n_caddr[c]),
      .n_wvalid(up && n_wvalid[c]), .n_wready(bwr), .n_wdata(n_wdata[c]), .n_wmask(n_wmask[c]),
      .n_rvalid(brv), .n_rdata(n_rdata[c]), .n_wdone(n_wdone[c]), .n_err(),
      .xclk, .xrst,
      .x_awvalid(1'b0), .x_awready(), .x_awid(4'h0), .x_awaddr(32'h0), .x_awlen(8'h0),
      .x_wvalid(1'b0), .x_wready(), .x_wdata(128'h0), .x_wstrb(16'h0), .x_wlast(1'b0),
      .x_bvalid(), .x_bready(1'b1), .x_bid(), .x_bresp(),
      .x_arvalid(1'b0), .x_arready(), .x_arid(4'h0), .x_araddr(32'h0), .x_arlen(8'h0),
      .x_rvalid(), .x_rready(1'b1), .x_rid(), .x_rdata(), .x_rresp(), .x_rlast(),
      .uclk, .urst,
      .c_cmd_valid(cv), .c_cmd_ready(cr), .c_cmd_we(cwe), .c_cmd_addr(ca),
      .c_wdata_valid(wv), .c_wdata_ready(wr), .c_wdata_data(wd), .c_wdata_we(we),
      .c_rdata_valid(rv), .c_rdata_data(rd));
    otpu_ldc_ch u_ctl (
      .sys_clk(uclk), .sys_rst(urst),
      .p0_cmd_valid(cv[0]), .p0_cmd_ready(cr[0]), .p0_cmd_we(cwe[0]), .p0_cmd_addr(ca[0]),
      .p0_wdata_valid(wv[0]), .p0_wdata_ready(wr[0]), .p0_wdata_data(wd[0]), .p0_wdata_we(we[0]),
      .p0_rdata_valid(lrv[0]), .p0_rdata_ready(1'b1), .p0_rdata_data(lrd[0]),
      .p1_cmd_valid(cv[1]), .p1_cmd_ready(cr[1]), .p1_cmd_we(cwe[1]), .p1_cmd_addr(ca[1]),
      .p1_wdata_valid(wv[1]), .p1_wdata_ready(wr[1]), .p1_wdata_data(wd[1]), .p1_wdata_we(we[1]),
      .p1_rdata_valid(lrv[1]), .p1_rdata_ready(1'b1), .p1_rdata_data(lrd[1]));
    // the controller's ports carry one read bus (the bridge reads port 0's only): the data is the
    // model's, on both ports, and the controller's own two buses must be the same every cycle
    assign rd[0] = rv[1] ? rdp[1] : rdp[0];
    assign rd[1] = rd[0];
    always @(posedge uclk)
      if (!urst && lrd[0] != lrd[1])
        $fatal(1, "otpu_ldc_mem: channel %0d: the controller's two read buses differ", c);

    // the data, per port in the controller's command order (a beat is always on the same port)
    for (genvar p = 0; p < 2; p++) begin : g_port
      oc_t          oq [$];              // commands the controller took, not yet done
      logic [511:0] qd [$];              // write data it took, not yet landed
      logic [63:0]  qm [$];
      always @(posedge uclk) begin
        if (urst) begin
          oq.delete(); qd.delete(); qm.delete();
          rv[p] <= 1'b0;
        end else begin
          if (cv[p] && cr[p]) oq.push_back('{cwe[p], ca[p]});
          if (wv[p] && wr[p]) begin
            qd.push_back(wd[p]);
            qm.push_back(we[p]);
          end
          // writes at the head land once their data is in
          while (oq.size() != 0 && oq[0].we && qd.size() != 0) begin
            int b;
            b = lbeat(32'(oq[0].m), c) * 16;
            for (int k = 0; k < 16; k++) begin
              logic [31:0] v;
              v = rdw(b + k);
              for (int j = 0; j < 4; j++)
                if (qm[0][4 * k + j]) v[8 * j +: 8] = qd[0][32 * k + 8 * j +: 8];
              wrw(b + k, v);
            end
            void'(oq.pop_front()); void'(qd.pop_front()); void'(qm.pop_front());
          end
          rv[p] <= 1'b0;
          if (lrv[p]) begin
            int b;
            if (oq.size() == 0 || oq[0].we)
              $fatal(1, "otpu_ldc_mem: channel %0d port %0d read data with no read at the head", c, p);
            b = lbeat(32'(oq[0].m), c) * 16;
            for (int k = 0; k < 16; k++) rdp[p][32 * k +: 32] <= rdw(b + k);
            rv[p] <= 1'b1;
            void'(oq.pop_front());
          end
        end
      end
    end
    // +ldc_break: the controller's cycles by what it does, each under the first that holds: a
    // column command on the DFI (data); refresh; a bank with a column command not issued (the
    // multiplexer); a bank with a command at its head and none of those (rows opening and
    // closing, a bank's timers); commands at the ports or in the banks' lookahead queues and none
    // at any bank's head (the crossbar); nothing (idle). From the first command to the last.
    // The idle gaps: their lengths, and the gaps after which the next command reads the next
    // channel beat of one of the last 4 read streams (a sequential prefetch could have filled
    // the gap with it: the cycles, up to 256 per gap).
`define OTPU_LDC_COL(p) (!u_ctl.core_dfi_p``p``_cs_n && !u_ctl.core_dfi_p``p``_cas_n && u_ctl.core_dfi_p``p``_ras_n)
`define OTPU_LDC_CR(n) (u_ctl.core_bankmachine``n``_cmd_valid && (u_ctl.core_bankmachine``n``_cmd_payload_is_read || u_ctl.core_bankmachine``n``_cmd_payload_is_write))
`define OTPU_LDC_HD(n) u_ctl.core_bankmachine``n``_pipe_valid_source_valid
`define OTPU_LDC_LV(n) (u_ctl.core_bankmachine``n``_level != 0)
    logic b_col, b_cr, b_hd, b_lv;
    assign b_col = `OTPU_LDC_COL(0) || `OTPU_LDC_COL(1) || `OTPU_LDC_COL(2) || `OTPU_LDC_COL(3);
    assign b_cr = `OTPU_LDC_CR(0) || `OTPU_LDC_CR(1) || `OTPU_LDC_CR(2) || `OTPU_LDC_CR(3) ||
                  `OTPU_LDC_CR(4) || `OTPU_LDC_CR(5) || `OTPU_LDC_CR(6) || `OTPU_LDC_CR(7);
    assign b_hd = `OTPU_LDC_HD(0) || `OTPU_LDC_HD(1) || `OTPU_LDC_HD(2) || `OTPU_LDC_HD(3) ||
                  `OTPU_LDC_HD(4) || `OTPU_LDC_HD(5) || `OTPU_LDC_HD(6) || `OTPU_LDC_HD(7);
    assign b_lv = `OTPU_LDC_LV(0) || `OTPU_LDC_LV(1) || `OTPU_LDC_LV(2) || `OTPU_LDC_LV(3) ||
                  `OTPU_LDC_LV(4) || `OTPU_LDC_LV(5) || `OTPU_LDC_LV(6) || `OTPU_LDC_LV(7);
    longint bk [6];                      // data, refresh, mux, rows, crossbar, idle
    longint bk_tail [6];                 // since the last command (not counted unless one follows)
    longint g_n [4], g_cyc [4];          // idle gaps of 1-7, 8-63, 64-255, 256+ cycles
    longint g_cont, g_cont_cyc;          // gaps of 8+ followed by a stream's next beat
    longint gap;
    bit     started, brk;
    int     sh [4];                      // the last 4 read streams' next channel beats
    initial begin
      brk = $test$plusargs("ldc_break");
      started = 0; gap = 0; g_cont = 0; g_cont_cyc = 0;
      for (int i = 0; i < 6; i++) begin bk[i] = 0; bk_tail[i] = 0; end
      for (int i = 0; i < 4; i++) begin g_n[i] = 0; g_cyc[i] = 0; sh[i] = -1; end
    end
    always @(posedge uclk) if (brk && !urst) begin
      int k;
      bit cmd;
      cmd = (cv[0] && cr[0]) || (cv[1] && cr[1]);
      k = b_col ? 0 : u_ctl.refresher_state != 0 ? 1 : b_cr ? 2 : b_hd ? 3 : (cv != 0 || b_lv) ? 4 : 5;
      if (started) bk_tail[k]++;
      if (k == 5) gap++;
      if (cmd) begin
        if (gap != 0) begin               // the gap ends with this cycle's command
          int j, a, hit;
          j = gap < 8 ? 0 : gap < 64 ? 1 : gap < 256 ? 2 : 3;
          if (started) begin g_n[j]++; g_cyc[j] += gap; end
          hit = 0;
          for (int p = 0; p < 2; p++)
            if (cv[p] && cr[p] && !cwe[p])
              for (int s = 0; s < 4; s++) if (int'(ca[p]) == sh[s]) hit = 1;
          if (started && gap >= 8 && hit != 0) begin
            g_cont++;
            g_cont_cyc += gap < 256 ? gap : 256;
          end
          gap = 0;
        end
        started = 1;
        for (int i = 0; i < 6; i++) begin bk[i] += bk_tail[i]; bk_tail[i] = 0; end
        for (int p = 0; p < 2; p++)       // the read streams: a read continuing one moves it up
          if (cv[p] && cr[p] && !cwe[p]) begin
            int s;
            s = 3;
            for (int i = 0; i < 4; i++) if (sh[i] == int'(ca[p])) s = i;
            for (int i = s; i > 0; i--) sh[i] = sh[i - 1];
            sh[0] = int'(ca[p]) + 1;
          end
      end
    end
`undef OTPU_LDC_COL
`undef OTPU_LDC_CR
`undef OTPU_LDC_HD
`undef OTPU_LDC_LV

    // the counts (row changes: each port's own, as the controller sees a master's commands)
    int pbr [2] = '{-1, -1};
    always @(posedge uclk) if (!urst)
      for (int p = 0; p < 2; p++)
        if (cv[p] && cr[p]) begin
          if (int'(ca[p] >> 7) != pbr[p]) n_miss[c]++;
          pbr[p] = int'(ca[p] >> 7);
          if (cwe[p]) n_wr[c]++; else n_rd[c]++;
        end
  end

  string dir;
  integer fd, nread;
  logic [31:0] chm [WORDS / 2];
  initial begin
    n_rd = '{0, 0}; n_wr = '{0, 0}; n_miss = '{0, 0};
    for (int i = 0; i < H; i++) mem_lo[i] = '0;
    for (int i = 0; i < WORDS - H; i++) mem_hi[i] = '0;
    if ($value$plusargs("dir=%s", dir)) begin
      if (PHYS == 0) begin
        fd = $fopen($sformatf("%s/dram_%0d.bin", dir, SID), "rb");
        if (fd != 0) begin
          nread = $fread(mem_lo, fd);  // the second continues where the first stopped
          nread = $fread(mem_hi, fd);
          $fclose(fd);
        end
      end else begin
        for (int c = 0; c < 2; c++) begin
          for (int i = 0; i < WORDS / 2; i++) chm[i] = '0;
          fd = $fopen($sformatf("%s/ch%0d.bin", dir, c), "rb");
          if (fd != 0) begin
            nread = $fread(chm, fd);
            $fclose(fd);
          end
          for (int j = 0; j < WORDS / 2; j++) wrw(lbeat(j / 16, c) * 16 + j % 16, chm[j]);
        end
      end
    end
  end
  always @(posedge clk) if (dump) begin
    for (int c = 0; c < 2; c++)
      $display("MEM ch%0d rd=%0d wr=%0d row_miss=%0d rmw=0", c, n_rd[c], n_wr[c], n_miss[c]);
    if (g_ch[0].brk) begin
      $display("BRK ch0 data=%0d ref=%0d mux=%0d rows=%0d xbar=%0d idle=%0d gaps=%0d/%0d/%0d/%0d gapcyc=%0d/%0d/%0d/%0d cont=%0d contcyc=%0d",
               g_ch[0].bk[0], g_ch[0].bk[1], g_ch[0].bk[2], g_ch[0].bk[3], g_ch[0].bk[4], g_ch[0].bk[5],
               g_ch[0].g_n[0], g_ch[0].g_n[1], g_ch[0].g_n[2], g_ch[0].g_n[3],
               g_ch[0].g_cyc[0], g_ch[0].g_cyc[1], g_ch[0].g_cyc[2], g_ch[0].g_cyc[3],
               g_ch[0].g_cont, g_ch[0].g_cont_cyc);
      $display("BRK ch1 data=%0d ref=%0d mux=%0d rows=%0d xbar=%0d idle=%0d gaps=%0d/%0d/%0d/%0d gapcyc=%0d/%0d/%0d/%0d cont=%0d contcyc=%0d",
               g_ch[1].bk[0], g_ch[1].bk[1], g_ch[1].bk[2], g_ch[1].bk[3], g_ch[1].bk[4], g_ch[1].bk[5],
               g_ch[1].g_n[0], g_ch[1].g_n[1], g_ch[1].g_n[2], g_ch[1].g_n[3],
               g_ch[1].g_cyc[0], g_ch[1].g_cyc[1], g_ch[1].g_cyc[2], g_ch[1].g_cyc[3],
               g_ch[1].g_cont, g_ch[1].g_cont_cyc);
    end
    if (PHYS == 0) begin
      fd = $fopen($sformatf("%s/dram_out_%0d.bin", dir, SID), "wb");
      for (int i = 0; i < WORDS; i++) $fwrite(fd, "%u", rdw(i));
      $fclose(fd);
    end else begin
      for (int c = 0; c < 2; c++) begin
        fd = $fopen($sformatf("%s/ch%0d_out.bin", dir, c), "wb");
        for (int j = 0; j < WORDS / 2; j++) $fwrite(fd, "%u", rdw(lbeat(j / 16, c) * 16 + j % 16));
        $fclose(fd);
      end
    end
  end
endmodule
