// Simulation model of the board memory behind the two channels' native ports n_*, as on the card
// (otpu_top AXI = 2): per channel the board's bridge otpu_mem_ch (clock crossing, read-modify-
// write of partial beats) in front of LiteDRAM's own controller (otpu_ldc_ch: bank machines,
// multiplexer, refresher, the crossbar with the idle BIST port, the ECC frontend; generated by
// tools/litedram/gen_ldc.py with the production core's settings, behind a DFI stub PHY with
// WL7DDRPHY's latencies), in the controller clock. The controller times every command; the data
// lives here, one logical image as otpu_native_mem holds it (the same parameters, ports, files and
// address map), and moves in the controller's command order: a write lands once the controller
// has taken its data, a read returns the memory as it is after every earlier command, when the
// controller returns it.
//
// Clocks: the core clock is the caller's (period 10 time units). The controller clock's period is
// 10 * +ldc_ratio=PPM / 1e6 units (PPM: core MHz / controller MHz * 1e6; default 1e6, the core at
// the controller's clock; rtlsim.ldc_plusargs), its edges on the nearest unit. The bridges' XDMA
// side is idle. The dump prints each channel's controller reads and writes and its row changes
// (MEM ch<c> rd=<n> wr=<n> row_miss=<row changes> rmw=0).
module otpu_ldc_mem #(
  parameter int WORDS = 1 << 18,
  parameter int PHYS  = 0,
  parameter int SID   = 0,
  parameter bit CHASH = 1'b1
) (
  input  logic                  clk,
  input  logic                  rst,
  input  logic [1:0]            n_cvalid,
  output logic [1:0]            n_cready,
  input  logic [1:0]            n_cwe,
  input  logic [1:0][24:0]      n_caddr,
  input  logic [1:0]            n_wvalid,
  output logic [1:0]            n_wready,
  input  logic [1:0][511:0]     n_wdata,
  input  logic [1:0][63:0]      n_wmask,
  output logic [1:0]            n_rvalid,
  output logic [1:0][511:0]     n_rdata,
  output logic [1:0][15:0]      n_wdone,
  input  logic                  dump
);
  // the image's words, as otpu_native_mem: word i is mem_lo[i] below H, else mem_hi[i - H]
  localparam int H = WORDS / 2;
  logic [31:0] mem_lo [H];
  logic [31:0] mem_hi [WORDS - H];
  function automatic logic [31:0] rdw(input int i);
    return i < H ? mem_lo[i] : mem_hi[i - H];
  endfunction
  task automatic wrw(input int i, input logic [31:0] v);
    if (i < H) mem_lo[i] = v;
    else mem_hi[i - H] = v;
  endtask
  // the logical beat of channel c's beat m (otpu_native_dram's map)
  function automatic int lbeat(input logic [31:0] m, input int c);
    return int'(m * 2 + (c[0] ^ (CHASH && ^m)));
  endfunction

  // clocks
  logic uclk = 1'b0, xclk = 1'b0;
  longint ratio = 1000000;
  // edge k at 5 * k * ratio units, one unit late and never on a multiple of 5: no controller edge
  // shares a time step with a core clock edge
  function automatic longint uedge(input longint k);
    longint t;
    t = (k * 5 * ratio + 500000) / 1000000 + 1;
    return (t % 5 == 0) ? t + 1 : t;
  endfunction
  initial begin
    longint k;
    k = 1;
    void'($value$plusargs("ldc_ratio=%d", ratio));
    #(uedge(1));
    forever begin
      uclk = ~uclk;
      #(uedge(k + 1) - uedge(k));
      k++;
    end
  end
  always #4 xclk = ~xclk;
  logic xrst = 1'b1, xr1 = 1'b1;
  always @(posedge xclk) {xrst, xr1} <= {xr1, rst};

  longint n_rd [2], n_wr [2], n_miss [2];
  typedef struct { logic we; logic [24:0] m; } oc_t;
  // the ports stay closed for the first 256 core cycles after rst, past the bridges' reset holds
  // (on the card the core waits for calibration)
  int upc = 0;
  logic up;
  always @(posedge clk) upc <= rst ? 0 : (upc < 256 ? upc + 1 : upc);
  assign up = upc == 256;

  for (genvar c = 0; c < 2; c++) begin : g_ch
    logic         urst = 1'b1, ur1 = 1'b1;
    logic         cv, cr, cwe, wv, wr, rv, lrv;
    logic [24:0]  ca;
    logic [511:0] wd, rd;
    logic [63:0]  we;
    logic         bcr, bwr, brv;
    always @(posedge uclk) {urst, ur1} <= {ur1, rst};
    assign n_cready[c] = up && bcr;
    assign n_wready[c] = up && bwr;
    assign n_rvalid[c] = up && brv;
    otpu_mem_ch #(.XIDW(4)) u_ch (
      .clk, .rst,
      .n_cvalid(up && n_cvalid[c]), .n_cready(bcr), .n_cwe(n_cwe[c]), .n_caddr(n_caddr[c]),
      .n_wvalid(up && n_wvalid[c]), .n_wready(bwr), .n_wdata(n_wdata[c]), .n_wmask(n_wmask[c]),
      .n_rvalid(brv), .n_rdata(n_rdata[c]), .n_wdone(n_wdone[c]),
      .xclk, .xrst,
      .x_awvalid(1'b0), .x_awready(), .x_awid(4'h0), .x_awaddr(32'h0), .x_awlen(8'h0),
      .x_wvalid(1'b0), .x_wready(), .x_wdata(128'h0), .x_wstrb(16'h0), .x_wlast(1'b0),
      .x_bvalid(), .x_bready(1'b1), .x_bid(), .x_bresp(),
      .x_arvalid(1'b0), .x_arready(), .x_arid(4'h0), .x_araddr(32'h0), .x_arlen(8'h0),
      .x_rvalid(), .x_rready(1'b1), .x_rid(), .x_rdata(), .x_rresp(), .x_rlast(),
      .uclk, .urst,
      .c_cmd_valid(cv), .c_cmd_ready(cr), .c_cmd_we(cwe), .c_cmd_addr(ca),
      .c_wdata_valid(wv), .c_wdata_ready(wr), .c_wdata_data(wd), .c_wdata_we(we),
      .c_rdata_valid(rv), .c_rdata_data(rd));
    otpu_ldc_ch u_ctl (
      .sys_clk(uclk), .sys_rst(urst),
      .cmd_valid(cv), .cmd_ready(cr), .cmd_we(cwe), .cmd_addr(ca),
      .wdata_valid(wv), .wdata_ready(wr), .wdata_data(wd), .wdata_we(we),
      .rdata_valid(lrv), .rdata_ready(1'b1), .rdata_data());

    // the data, in the controller's command order
    oc_t          oq [$];                // commands the controller took, not yet done
    logic [511:0] qd [$];                // write data it took, not yet landed
    logic [63:0]  qm [$];
    int           pbr = -1;
    always @(posedge uclk) begin
      if (urst) begin
        oq.delete(); qd.delete(); qm.delete();
        rv <= 1'b0;
      end else begin
        if (cv && cr) begin
          oq.push_back('{cwe, ca});
          if (int'(ca >> 7) != pbr) n_miss[c]++;
          pbr = int'(ca >> 7);
          if (cwe) n_wr[c]++; else n_rd[c]++;
        end
        if (wv && wr) begin
          qd.push_back(wd);
          qm.push_back(we);
        end
        // writes at the head land once their data is in
        while (oq.size() != 0 && oq[0].we && qd.size() != 0) begin
          int b;
          b = lbeat(32'(oq[0].m), c) * 16;
          for (int k = 0; k < 16; k++) begin
            logic [31:0] v;
            v = rdw(b + k);
            for (int j = 0; j < 4; j++)
              if (qm[0][4 * k + j]) v[8 * j +: 8] = qd[0][32 * k + 8 * j +: 8];
            wrw(b + k, v);
          end
          void'(oq.pop_front()); void'(qd.pop_front()); void'(qm.pop_front());
        end
        rv <= 1'b0;
        if (lrv) begin
          int b;
          if (oq.size() == 0 || oq[0].we)
            $fatal(1, "otpu_ldc_mem: channel %0d read data with no read at the head", c);
          b = lbeat(32'(oq[0].m), c) * 16;
          for (int k = 0; k < 16; k++) rd[32 * k +: 32] <= rdw(b + k);
          rv <= 1'b1;
          void'(oq.pop_front());
        end
      end
    end
  end

  string dir;
  integer fd, nread;
  logic [31:0] chm [WORDS / 2];
  initial begin
    n_rd = '{0, 0}; n_wr = '{0, 0}; n_miss = '{0, 0};
    for (int i = 0; i < H; i++) mem_lo[i] = '0;
    for (int i = 0; i < WORDS - H; i++) mem_hi[i] = '0;
    if ($value$plusargs("dir=%s", dir)) begin
      if (PHYS == 0) begin
        fd = $fopen($sformatf("%s/dram_%0d.bin", dir, SID), "rb");
        if (fd != 0) begin
          nread = $fread(mem_lo, fd);  // the second continues where the first stopped
          nread = $fread(mem_hi, fd);
          $fclose(fd);
        end
      end else begin
        for (int c = 0; c < 2; c++) begin
          for (int i = 0; i < WORDS / 2; i++) chm[i] = '0;
          fd = $fopen($sformatf("%s/ch%0d.bin", dir, c), "rb");
          if (fd != 0) begin
            nread = $fread(chm, fd);
            $fclose(fd);
          end
          for (int j = 0; j < WORDS / 2; j++) wrw(lbeat(j / 16, c) * 16 + j % 16, chm[j]);
        end
      end
    end
  end
  always @(posedge clk) if (dump) begin
    for (int c = 0; c < 2; c++)
      $display("MEM ch%0d rd=%0d wr=%0d row_miss=%0d rmw=0", c, n_rd[c], n_wr[c], n_miss[c]);
    if (PHYS == 0) begin
      fd = $fopen($sformatf("%s/dram_out_%0d.bin", dir, SID), "wb");
      for (int i = 0; i < WORDS; i++) $fwrite(fd, "%u", rdw(i));
      $fclose(fd);
    end else begin
      for (int c = 0; c < 2; c++) begin
        fd = $fopen($sformatf("%s/ch%0d_out.bin", dir, c), "wb");
        for (int j = 0; j < WORDS / 2; j++) $fwrite(fd, "%u", rdw(lbeat(j / 16, c) * 16 + j % 16));
        $fclose(fd);
      end
    end
  end
endmodule
