#!/usr/bin/env bash
# Is the committed LiteDRAM core what tools/litedram/gen_core.py makes? Regenerates it and compares
# it with boards/ypcb-00338/litedram/ (otpu_litedram.v, otpu_litedram.xdc, the sha256s in
# core.json) and its csr.csv / sdram_init.py with opentpu/host/litedram/. Exit 1 on any drift.
#
#   tools/litedram/check_core.sh                  # PYTHON (default: $LITEX_VENV/bin/python)
#   tools/litedram/check_core.sh --setup DIR      # first make DIR a venv (uv) with migen, litex and
#                                                 # litedram at core.json's commits, then check
#   tools/litedram/check_core.sh --update         # regenerate and overwrite the committed core and
#                                                 # host files, rewrite core.json's hashes
#
# LiteX is not part of the repository's environment (the Vivado hosts have none): any Python with
# those three packages at core.json's commits will do, e.g. the one tools/litedram was developed
# with. A regenerated core differs from the committed one only in its generation date and in the
# order of the instance tree LiteX prints in a comment; both are left out of the comparison, the
# Verilog itself must match line for line.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
core="$root/boards/ypcb-00338/litedram"
host="$root/opentpu/host/litedram"
update=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --setup)
      venv="$2"; shift 2
      pkgs=$(python3 -c "import json,sys; p=json.load(open(sys.argv[1]))['packages']
print(' '.join(f\"git+{v['url']}@{v['commit']}\" for v in p.values()))" "$core/core.json")
      uv venv --python 3.11 "$venv"
      # shellcheck disable=SC2086
      VIRTUAL_ENV="$venv" uv pip install $pkgs
      LITEX_VENV="$venv";;
    --update) update=1; shift;;
    *) echo "usage: $0 [--setup DIR] [--update]" >&2; exit 2;;
  esac
done
py="${PYTHON:-${LITEX_VENV:+$LITEX_VENV/bin/python}}"
if [[ -z "$py" ]]; then echo "set PYTHON or LITEX_VENV (or --setup DIR)" >&2; exit 2; fi

out="$(mktemp -d "${TMPDIR:-/tmp}/otpu_core.XXXXXX")"
trap 'rm -rf "$out"' EXIT
# gen_core.py's arguments as core.json records them ("<dir>": the output directory)
args=()
while IFS= read -r a; do args+=("$a"); done < <(python3 -c "import json,sys
for a in json.load(open(sys.argv[1]))['args']: print('core' if a == '<dir>' else a)" "$core/core.json")
(cd "$out" && "$py" "$here/gen_core.py" "${args[@]}" > gen.log 2>&1) || { tail -20 "$out/gen.log"; exit 1; }
new="$out/core"

# the generated Verilog without its date and its instance-tree comment
norm_v() { awk '$0 == "/*" {skip = 1} !skip && !/Date       :/ && !/Auto-Generated by LiteX on/ {print} $0 == "*/" {skip = 0}' "$1"; }
norm_csv() { grep -v '^#' "$1"; }

if [[ $update == 1 ]]; then
  cp "$new/otpu_litedram.v" "$new/otpu_litedram.xdc" "$core/"
  cp "$new/csr.csv" "$new/sdram_init.py" "$host/"
  python3 - "$core/core.json" "$core" <<'EOF'
import hashlib, json, sys
from pathlib import Path
p, d = Path(sys.argv[1]), Path(sys.argv[2])
info = json.loads(p.read_text())
info["sha256"] = {f.name: hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(d.glob("otpu_litedram.*"))}
p.write_text(json.dumps(info, indent=1) + "\n")
EOF
  echo "core updated in $core (and csr.csv, sdram_init.py in $host); commit them together"
  echo "(a changed port list: boards/ypcb-00338/sim/otpu_litedram_stub.sv too, which"
  echo " boards/ypcb-00338/scripts/check_offline.py --mem litedram compares)"
  exit 0
fi

fail=0
(cd "$core" && python3 - <<'EOF') || fail=1
import hashlib, json
info = json.load(open("core.json"))
for name, h in info["sha256"].items():
    got = hashlib.sha256(open(name, "rb").read()).hexdigest()
    if got != h:
        print(f"{name}: sha256 {got}, core.json says {h}")
        raise SystemExit(1)
EOF
if ! diff -q <(norm_v "$core/otpu_litedram.v") <(norm_v "$new/otpu_litedram.v") > /dev/null; then
  echo "otpu_litedram.v differs from gen_core.py's:"; diff <(norm_v "$core/otpu_litedram.v") <(norm_v "$new/otpu_litedram.v") | head -20; fail=1
fi
cmp -s "$core/otpu_litedram.xdc" "$new/otpu_litedram.xdc" || { echo "otpu_litedram.xdc differs"; fail=1; }
diff -q <(norm_csv "$host/csr.csv") <(norm_csv "$new/csr.csv") > /dev/null || { echo "csr.csv differs"; fail=1; }
cmp -s "$host/sdram_init.py" "$new/sdram_init.py" || { echo "sdram_init.py differs"; fail=1; }
if [[ $fail == 0 ]]; then echo "LiteDRAM core: matches gen_core.py"; else echo "LiteDRAM core: DRIFT"; fi
exit $fail
