// FPGA top for the Inspur YPCB-00338 (xc7k480t-ffg1156-2) with LiteDRAM (create_project.tcl):
// the block design otpu_bd (PCIe XDMA, the core clock, the XADC, the control interconnect;
// boards/ypcb-00338/vivado/bd_native.tcl), the LiteDRAM core otpu_litedram (both DDR3 channels at
// 72 bits, DDR3-1066, WL7DDRPHY, generated by tools/litedram/gen_core.py --phy wl:
// boards/ypcb-00338/litedram/) and
// otpu_native_sys: the accelerator on the channels' native ports (otpu_board: otpu_native_dram)
// and XDMA's DMA master (split by address bit 31), meeting in one otpu_mem_ch per channel (which
// read-modify-writes partial beats: LiteDRAM's ECC port takes whole beats only). XDMA's AXI-Lite
// master (BAR0) reaches the control registers at 0x0, the LiteDRAM CSRs at 0x10000 (the host
// calibrates the channels: opentpu/host/memcal.py, CAPS bit27, HOSTCAL) and the XADC at 0x30000.
//
// Clocks: the 50 MHz oscillator, on one global buffer, feeds the block design's MMCM (core_clk)
// and the LiteDRAM core's (its sys_clk, 133.33 MHz, the channels' controller side; each
// channel's DDR3 clocks from a write clock MMCM cascaded from sys, placed by otpu_top_ld.xdc);
// xdma_aclk (125 MHz; 250 at PCIE_GEN 2) is XDMA's. otpu_mem_ch crosses between the three; the
// LiteDRAM core crosses its CSR port into sys_clk itself, from xdma_aclk (from core_clk at
// PCIE_GEN 2, where the block design's SmartConnect puts M_AXI_MEMCAL on core_clk).
// constraints/otpu_top_native.tcl and otpu_mem_ch.tcl constrain the crossings (no asynchronous
// clock groups: their max delays must stay in force).
// Resets: core_rst from the block design (MMCM lock, PCIe PERST#), xrst from XDMA's axi_aresetn;
// the LiteDRAM core has none (its MMCMs' lock resets it), so a PCIe reset or a host driver
// restart keeps the channels calibrated, and only a new configuration needs the host to
// calibrate them again. The core's CSR port crosses into its sys clock through FIFOs whose two
// sides must reset together: its ctl side resets with the core's sys reset (ld_sys_rst, brought
// into the CSR clock), not with PERST# (a ctl side reset alone left the sys side's pointers ahead,
// and the sys side replayed old CSR accesses: calibration, BIST, DFII writes). The block design's
// SmartConnect, the CSR port's and the control registers' master, resets with axi_aresetn (PERST#,
// hot reset, link down); otpu_axil_iso (otpu_ctrl.sv) in front of each completes an access in
// flight at its reset and drops the response, so neither answers the reset master.
// DDR3 port names are the LiteDRAM core's (ddram0_*, ddram1_*), so its XDC places them.
module otpu_fpga_top_ld #(
  parameter int MCOLS = 4,                  // MXU columns (activation rows per weight chunk)
  parameter int ACT_ROWS = MCOLS,           // ACT RAM rows (> MCOLS: MM replay, one weight pass)
  parameter int VPU_CL = 2,                 // VPU lanes with the composite functions (exp2, ...)
  parameter int MXU_IMPL = 2,               // MXU dot product: 2 systolic (docs/mxu_systolic.md), 0 adder tree
  parameter int LANES = 8,                  // VPU lanes / TMEM banks (8 or 16)
  parameter int ULANES = 8,                 // TMEM lanes of the MXU and the quantizer
  parameter int CORE_KHZ = 100000,          // core_clk as the block design makes it (CORE_KHZ register)
  parameter logic [31:0] BUILD_ID = 32'h0,  // the git commit (BUILD_ID register)
  parameter int DDR_MTS = 1066,             // the DDR3 data rate the LiteDRAM core runs (DDR_MTS register)
  parameter bit DSTEP = 1'b1,               // the DMA's DSTEP datapath (CAPS bit6; 0: left out)
  parameter int PCIE_GEN = 1                // 1: Gen1 x8, xdma_aclk 125 MHz; 2: Gen2 x8, 250 MHz,
                                            // slices to the bridges (otpu_native_sys XREG),
                                            // the LiteDRAM CSRs on core_clk (bd_native.tcl)
) (
  // board
  input  logic        SYS_CLK,              // 50 MHz, AA28
  output logic [2:0]  led,                  // P30 red, M30 green, N30 yellow
  // I2C, open drain (otpu_ctrl I2C_CTRL / I2C_IN; the host bit-bangs them)
  inout  wire         lm73_scl,             // N24  the LM73 temperature sensor's bus
  inout  wire         lm73_sda,             // N25
  input  logic        lm73_alert_n,         // P25
  inout  wire         smb_scl,              // R26  the PCIe edge connector's SMBus
  inout  wire         smb_sda,              // R27
  // PCIe Gen2 x8
  input  logic        pcie_refclk_clk_p,    // J8 (MGTREFCLK)
  input  logic        pcie_refclk_clk_n,
  input  logic        pcie_perstn,          // Y26
  input  logic [7:0]  pcie_mgt_rxp,
  input  logic [7:0]  pcie_mgt_rxn,
  output logic [7:0]  pcie_mgt_txp,
  output logic [7:0]  pcie_mgt_txn,
  // DDR3 channel 0
  inout  wire  [71:0] ddram0_dq,
  inout  wire  [8:0]  ddram0_dqs_p,
  inout  wire  [8:0]  ddram0_dqs_n,
  output logic [14:0] ddram0_a,
  output logic [2:0]  ddram0_ba,
  output logic        ddram0_ras_n,
  output logic        ddram0_cas_n,
  output logic        ddram0_we_n,
  output logic        ddram0_reset_n,
  output logic        ddram0_clk_p,
  output logic        ddram0_clk_n,
  output logic        ddram0_cke,
  output logic        ddram0_cs_n,
  output logic        ddram0_odt,
  // DDR3 channel 1
  inout  wire  [71:0] ddram1_dq,
  inout  wire  [8:0]  ddram1_dqs_p,
  inout  wire  [8:0]  ddram1_dqs_n,
  output logic [14:0] ddram1_a,
  output logic [2:0]  ddram1_ba,
  output logic        ddram1_ras_n,
  output logic        ddram1_cas_n,
  output logic        ddram1_we_n,
  output logic        ddram1_reset_n,
  output logic        ddram1_clk_p,
  output logic        ddram1_clk_n,
  output logic        ddram1_cke,
  output logic        ddram1_cs_n,
  output logic        ddram1_odt
);
  logic        clk50_ib, clk50;
  logic        core_clk, core_rstn, xdma_aclk, xdma_aresetn, pcie_link_up;
  logic        ld_sys_clk, ld_sys_rst;
  logic [1:0]  calib, ded;
  logic [11:0] device_temp;                  // XADC die-temperature code (core_clk)

  // the 50 MHz oscillator on one global buffer: the block design's MMCM and the LiteDRAM core's
  IBUF u_ibuf50 (.I(SYS_CLK), .O(clk50_ib));
  BUFG u_bufg50 (.I(clk50_ib), .O(clk50));

  // ---- control (AXI4-Lite, BD master -> accelerator, core_clk)
  logic [31:0] ctl_awaddr, ctl_araddr, ctl_wdata, ctl_rdata;
  logic [3:0]  ctl_wstrb;
  logic [1:0]  ctl_bresp, ctl_rresp;
  logic ctl_awvalid, ctl_awready, ctl_wvalid, ctl_wready, ctl_bvalid, ctl_bready;
  logic ctl_arvalid, ctl_arready, ctl_rvalid, ctl_rready;
  // ---- the LiteDRAM CSRs (AXI4-Lite, BD master -> the core; xdma_aclk, core_clk at PCIE_GEN 2)
  logic [31:0] mc_awaddr, mc_araddr, mc_wdata, mc_rdata;
  logic [3:0]  mc_wstrb;
  logic [1:0]  mc_bresp, mc_rresp;
  logic mc_awvalid, mc_awready, mc_wvalid, mc_wready, mc_bvalid, mc_bready;
  logic mc_arvalid, mc_arready, mc_rvalid, mc_rready;
  // ---- XDMA's DMA master (AXI4, 128 bits, xdma_aclk)
  logic [3:0]   dm_awid, dm_arid, dm_bid, dm_rid;
  logic [63:0]  dm_awaddr, dm_araddr;
  logic [7:0]   dm_awlen, dm_arlen;
  logic [127:0] dm_wdata, dm_rdata;
  logic [15:0]  dm_wstrb;
  logic [1:0]   dm_bresp, dm_rresp;
  logic dm_awvalid, dm_awready, dm_wlast, dm_wvalid, dm_wready, dm_bvalid, dm_bready;
  logic dm_arvalid, dm_arready, dm_rlast, dm_rvalid, dm_rready;

  otpu_bd_wrapper u_bd (
    .sys_clk_50(clk50),
    .pcie_refclk_clk_p, .pcie_refclk_clk_n, .pcie_perstn,
    .pcie_mgt_rxp, .pcie_mgt_rxn, .pcie_mgt_txp, .pcie_mgt_txn,
    .pcie_link_up, .core_clk, .core_rstn, .xdma_aclk, .xdma_aresetn, .device_temp,
    .M_AXI_CTL_awaddr(ctl_awaddr), .M_AXI_CTL_awvalid(ctl_awvalid),
    .M_AXI_CTL_awready(ctl_awready), .M_AXI_CTL_wdata(ctl_wdata), .M_AXI_CTL_wstrb(ctl_wstrb),
    .M_AXI_CTL_wvalid(ctl_wvalid), .M_AXI_CTL_wready(ctl_wready),
    .M_AXI_CTL_bresp(ctl_bresp), .M_AXI_CTL_bvalid(ctl_bvalid), .M_AXI_CTL_bready(ctl_bready),
    .M_AXI_CTL_araddr(ctl_araddr), .M_AXI_CTL_arvalid(ctl_arvalid),
    .M_AXI_CTL_arready(ctl_arready), .M_AXI_CTL_rdata(ctl_rdata), .M_AXI_CTL_rresp(ctl_rresp),
    .M_AXI_CTL_rvalid(ctl_rvalid), .M_AXI_CTL_rready(ctl_rready),
    .M_AXI_MEMCAL_awaddr(mc_awaddr), .M_AXI_MEMCAL_awvalid(mc_awvalid),
    .M_AXI_MEMCAL_awready(mc_awready), .M_AXI_MEMCAL_wdata(mc_wdata),
    .M_AXI_MEMCAL_wstrb(mc_wstrb), .M_AXI_MEMCAL_wvalid(mc_wvalid),
    .M_AXI_MEMCAL_wready(mc_wready), .M_AXI_MEMCAL_bresp(mc_bresp),
    .M_AXI_MEMCAL_bvalid(mc_bvalid), .M_AXI_MEMCAL_bready(mc_bready),
    .M_AXI_MEMCAL_araddr(mc_araddr), .M_AXI_MEMCAL_arvalid(mc_arvalid),
    .M_AXI_MEMCAL_arready(mc_arready), .M_AXI_MEMCAL_rdata(mc_rdata),
    .M_AXI_MEMCAL_rresp(mc_rresp), .M_AXI_MEMCAL_rvalid(mc_rvalid),
    .M_AXI_MEMCAL_rready(mc_rready),
    .M_AXI_DMA_awid(dm_awid), .M_AXI_DMA_awaddr(dm_awaddr), .M_AXI_DMA_awlen(dm_awlen),
    .M_AXI_DMA_awvalid(dm_awvalid), .M_AXI_DMA_awready(dm_awready),
    .M_AXI_DMA_wdata(dm_wdata), .M_AXI_DMA_wstrb(dm_wstrb), .M_AXI_DMA_wlast(dm_wlast),
    .M_AXI_DMA_wvalid(dm_wvalid), .M_AXI_DMA_wready(dm_wready),
    .M_AXI_DMA_bid(dm_bid), .M_AXI_DMA_bresp(dm_bresp), .M_AXI_DMA_bvalid(dm_bvalid),
    .M_AXI_DMA_bready(dm_bready),
    .M_AXI_DMA_arid(dm_arid), .M_AXI_DMA_araddr(dm_araddr), .M_AXI_DMA_arlen(dm_arlen),
    .M_AXI_DMA_arvalid(dm_arvalid), .M_AXI_DMA_arready(dm_arready),
    .M_AXI_DMA_rid(dm_rid), .M_AXI_DMA_rdata(dm_rdata), .M_AXI_DMA_rresp(dm_rresp),
    .M_AXI_DMA_rlast(dm_rlast), .M_AXI_DMA_rvalid(dm_rvalid), .M_AXI_DMA_rready(dm_rready),
    // XDMA's bursts are INCR of full-width beats (otpu_mem_ch relies on it): these are unused
    .M_AXI_DMA_awsize(), .M_AXI_DMA_awburst(), .M_AXI_DMA_awlock(), .M_AXI_DMA_awcache(),
    .M_AXI_DMA_awprot(), .M_AXI_DMA_arsize(), .M_AXI_DMA_arburst(), .M_AXI_DMA_arlock(),
    .M_AXI_DMA_arcache(), .M_AXI_DMA_arprot()
  );

  // resets: synchronous, active high, one register each (otpu_mem_ch crosses them registered)
  logic core_rst, xrst;
  always_ff @(posedge core_clk) core_rst <= !core_rstn;
  always_ff @(posedge xdma_aclk) xrst <= !xdma_aresetn;
  // the SmartConnect's reset (axi_aresetn) in core_clk, where its control masters are (M_AXI_CTL;
  // M_AXI_MEMCAL at PCIE_GEN 2): the masters' side of otpu_axil_iso. Two flip-flops
  // (otpu_top_native.tcl: one core_clk period from xdma_aclk); the reset lasts many cycles
  (* ASYNC_REG = "TRUE" *) logic lrs1 = 1'b1, lrs2 = 1'b1;
  always_ff @(posedge core_clk) begin lrs1 <= xrst; lrs2 <= lrs1; end

  // ---- the channels' controller ports (otpu_mem_ch <-> the LiteDRAM core), sys_clk: two per
  // channel, [channel][port] (port 1 = the core's c<n>b_*: the odd banks)
  logic [1:0][1:0]        c_cmd_valid, c_cmd_ready, c_cmd_we, c_wdata_valid, c_wdata_ready;
  logic [1:0][1:0]        c_rdata_valid;
  logic [1:0]             c_ready;
  logic [1:0][1:0][24:0]  c_cmd_addr;
  logic [1:0][1:0][511:0] c_wdata_data, c_rdata_data;
  logic [1:0][1:0][63:0]  c_wdata_we;

  // ---- LiteDRAM: both channels, their CSRs (BAR0 0x10000) and calibration ready bits
  // The CSR port's clock (ctl_clk: core_clk at PCIE_GEN 2, else xdma_aclk) and reset: the core's
  // sys reset, in that clock through two flip-flops (otpu_top_native.tcl: one ctl_clk period
  // from sys), so the crossing's two sides reset together, at configuration and when the core's
  // clocks lose lock, never on PERST#
  wire ld_ctl_clk = PCIE_GEN == 2 ? core_clk : xdma_aclk;
  (* ASYNC_REG = "TRUE" *) logic ld_crs1 = 1'b1, ld_crs2 = 1'b1;
  always_ff @(posedge ld_ctl_clk) begin ld_crs1 <= ld_sys_rst; ld_crs2 <= ld_crs1; end
  // the CSR port behind otpu_axil_iso: the SmartConnect's reset (lrs2 in core_clk; xrst in
  // xdma_aclk at PCIE_GEN 1) is its master's
  logic [15:0] lc_awaddr, lc_araddr;
  logic [31:0] lc_wdata, lc_rdata;
  logic [3:0]  lc_wstrb;
  logic [1:0]  lc_bresp, lc_rresp;
  logic lc_awvalid, lc_awready, lc_wvalid, lc_wready, lc_bvalid, lc_bready;
  logic lc_arvalid, lc_arready, lc_rvalid, lc_rready;
  otpu_axil_iso #(.AW(16)) u_mc_iso (
    .clk(ld_ctl_clk), .m_rst(PCIE_GEN == 2 ? lrs2 : xrst), .s_rst(ld_crs2),
    .m_awaddr(mc_awaddr[15:0]), .m_awvalid(mc_awvalid), .m_awready(mc_awready),
    .m_wdata(mc_wdata), .m_wstrb(mc_wstrb), .m_wvalid(mc_wvalid), .m_wready(mc_wready),
    .m_bresp(mc_bresp), .m_bvalid(mc_bvalid), .m_bready(mc_bready),
    .m_araddr(mc_araddr[15:0]), .m_arvalid(mc_arvalid), .m_arready(mc_arready),
    .m_rdata(mc_rdata), .m_rresp(mc_rresp), .m_rvalid(mc_rvalid), .m_rready(mc_rready),
    .s_awaddr(lc_awaddr), .s_awvalid(lc_awvalid), .s_awready(lc_awready), .s_wdata(lc_wdata),
    .s_wstrb(lc_wstrb), .s_wvalid(lc_wvalid), .s_wready(lc_wready), .s_bresp(lc_bresp),
    .s_bvalid(lc_bvalid), .s_bready(lc_bready), .s_araddr(lc_araddr), .s_arvalid(lc_arvalid),
    .s_arready(lc_arready), .s_rdata(lc_rdata), .s_rresp(lc_rresp), .s_rvalid(lc_rvalid),
    .s_rready(lc_rready));
  otpu_litedram u_ld (
    .clk50g(clk50), .rst(1'b0), .sys_clk(ld_sys_clk), .sys_rst(ld_sys_rst),
    .ctl_clk(ld_ctl_clk), .ctl_rst(ld_crs2),
    .ctl_awvalid(lc_awvalid), .ctl_awready(lc_awready), .ctl_awaddr(lc_awaddr),
    .ctl_wvalid(lc_wvalid), .ctl_wready(lc_wready), .ctl_wdata(lc_wdata), .ctl_wstrb(lc_wstrb),
    .ctl_bvalid(lc_bvalid), .ctl_bready(lc_bready), .ctl_bresp(lc_bresp),
    .ctl_arvalid(lc_arvalid), .ctl_arready(lc_arready), .ctl_araddr(lc_araddr),
    .ctl_rvalid(lc_rvalid), .ctl_rready(lc_rready), .ctl_rdata(lc_rdata), .ctl_rresp(lc_rresp),
    .c0_cmd_valid(c_cmd_valid[0][0]), .c0_cmd_ready(c_cmd_ready[0][0]), .c0_cmd_we(c_cmd_we[0][0]),
    .c0_cmd_addr(c_cmd_addr[0][0]), .c0_wdata_valid(c_wdata_valid[0][0]),
    .c0_wdata_ready(c_wdata_ready[0][0]), .c0_wdata_data(c_wdata_data[0][0]),
    .c0_wdata_we(c_wdata_we[0][0]), .c0_rdata_valid(c_rdata_valid[0][0]), .c0_rdata_ready(1'b1),
    .c0_rdata_data(c_rdata_data[0][0]), .c0_ready(c_ready[0]), .c0_ded(ded[0]),
    .c0b_cmd_valid(c_cmd_valid[0][1]), .c0b_cmd_ready(c_cmd_ready[0][1]), .c0b_cmd_we(c_cmd_we[0][1]),
    .c0b_cmd_addr(c_cmd_addr[0][1]), .c0b_wdata_valid(c_wdata_valid[0][1]),
    .c0b_wdata_ready(c_wdata_ready[0][1]), .c0b_wdata_data(c_wdata_data[0][1]),
    .c0b_wdata_we(c_wdata_we[0][1]), .c0b_rdata_valid(c_rdata_valid[0][1]), .c0b_rdata_ready(1'b1),
    .c0b_rdata_data(c_rdata_data[0][1]),
    .c1_cmd_valid(c_cmd_valid[1][0]), .c1_cmd_ready(c_cmd_ready[1][0]), .c1_cmd_we(c_cmd_we[1][0]),
    .c1_cmd_addr(c_cmd_addr[1][0]), .c1_wdata_valid(c_wdata_valid[1][0]),
    .c1_wdata_ready(c_wdata_ready[1][0]), .c1_wdata_data(c_wdata_data[1][0]),
    .c1_wdata_we(c_wdata_we[1][0]), .c1_rdata_valid(c_rdata_valid[1][0]), .c1_rdata_ready(1'b1),
    .c1_rdata_data(c_rdata_data[1][0]), .c1_ready(c_ready[1]), .c1_ded(ded[1]),
    .c1b_cmd_valid(c_cmd_valid[1][1]), .c1b_cmd_ready(c_cmd_ready[1][1]), .c1b_cmd_we(c_cmd_we[1][1]),
    .c1b_cmd_addr(c_cmd_addr[1][1]), .c1b_wdata_valid(c_wdata_valid[1][1]),
    .c1b_wdata_ready(c_wdata_ready[1][1]), .c1b_wdata_data(c_wdata_data[1][1]),
    .c1b_wdata_we(c_wdata_we[1][1]), .c1b_rdata_valid(c_rdata_valid[1][1]), .c1b_rdata_ready(1'b1),
    .c1b_rdata_data(c_rdata_data[1][1]),
    .ddram0_dq, .ddram0_dqs_p, .ddram0_dqs_n, .ddram0_a, .ddram0_ba, .ddram0_ras_n,
    .ddram0_cas_n, .ddram0_we_n, .ddram0_reset_n, .ddram0_clk_p, .ddram0_clk_n, .ddram0_cke,
    .ddram0_cs_n, .ddram0_odt,
    .ddram1_dq, .ddram1_dqs_p, .ddram1_dqs_n, .ddram1_a, .ddram1_ba, .ddram1_ras_n,
    .ddram1_cas_n, .ddram1_we_n, .ddram1_reset_n, .ddram1_clk_p, .ddram1_clk_n, .ddram1_cke,
    .ddram1_cs_n, .ddram1_odt);
  assign calib = c_ready;                   // STATUS CALIB0/1 (sys_clk; otpu_board syncs them)
                                            // ded: STATUS ECC_DED (the same)

  // I2C: each line released (high-Z, pulled up) unless its I2C_CTRL bit drives it low
  logic [3:0] i2c_lo, i2c_lvl;
  IOBUF u_iob_scl0 (.IO(lm73_scl), .I(1'b0), .T(!i2c_lo[0]), .O(i2c_lvl[0]));
  IOBUF u_iob_sda0 (.IO(lm73_sda), .I(1'b0), .T(!i2c_lo[1]), .O(i2c_lvl[1]));
  IOBUF u_iob_scl1 (.IO(smb_scl),  .I(1'b0), .T(!i2c_lo[2]), .O(i2c_lvl[2]));
  IOBUF u_iob_sda1 (.IO(smb_sda),  .I(1'b0), .T(!i2c_lo[3]), .O(i2c_lvl[3]));

  // ---- the accelerator and XDMA on the channels
  logic [2:0] board_led;
  otpu_native_sys #(.MCOLS(MCOLS), .ACT_ROWS(ACT_ROWS), .VPU_CL(VPU_CL), .MXU_IMPL(MXU_IMPL),
                    .LANES(LANES),
                    .ULANES(ULANES), .CORE_KHZ(CORE_KHZ), .BUILD_ID(BUILD_ID), .DDR_MTS(DDR_MTS),
                    .DSTEP(DSTEP), .HOSTCAL(1'b1), .XREG(PCIE_GEN == 2)) u_sys (
    .clk(core_clk), .rst(core_rst), .ctl_mrst(lrs2), .xclk(xdma_aclk), .xrst,
    .calib, .ded, .temp(device_temp), .led(board_led), .i2c_lo, .i2c_pin({lm73_alert_n, i2c_lvl}),
    .s_ctl_awaddr(ctl_awaddr[11:0]), .s_ctl_awvalid(ctl_awvalid), .s_ctl_awready(ctl_awready),
    .s_ctl_wdata(ctl_wdata), .s_ctl_wstrb(ctl_wstrb), .s_ctl_wvalid(ctl_wvalid),
    .s_ctl_wready(ctl_wready), .s_ctl_bresp(ctl_bresp), .s_ctl_bvalid(ctl_bvalid),
    .s_ctl_bready(ctl_bready), .s_ctl_araddr(ctl_araddr[11:0]), .s_ctl_arvalid(ctl_arvalid),
    .s_ctl_arready(ctl_arready), .s_ctl_rdata(ctl_rdata), .s_ctl_rresp(ctl_rresp),
    .s_ctl_rvalid(ctl_rvalid), .s_ctl_rready(ctl_rready),
    .x_awvalid(dm_awvalid), .x_awready(dm_awready), .x_awid(dm_awid), .x_awaddr(dm_awaddr[31:0]),
    .x_awlen(dm_awlen), .x_wvalid(dm_wvalid), .x_wready(dm_wready), .x_wdata(dm_wdata),
    .x_wstrb(dm_wstrb), .x_wlast(dm_wlast), .x_bvalid(dm_bvalid), .x_bready(dm_bready),
    .x_bid(dm_bid), .x_bresp(dm_bresp), .x_arvalid(dm_arvalid), .x_arready(dm_arready),
    .x_arid(dm_arid), .x_araddr(dm_araddr[31:0]), .x_arlen(dm_arlen), .x_rvalid(dm_rvalid),
    .x_rready(dm_rready), .x_rid(dm_rid), .x_rdata(dm_rdata), .x_rresp(dm_rresp),
    .x_rlast(dm_rlast),
    .uclk({2{ld_sys_clk}}), .urst({2{ld_sys_rst}}),
    .c_cmd_valid, .c_cmd_ready, .c_cmd_we, .c_cmd_addr, .c_wdata_valid,
    .c_wdata_ready, .c_wdata_data, .c_wdata_we, .c_rdata_valid, .c_rdata_data);

  // LEDs: led[0] red = heartbeat, led[1] green = PCIe link up and both DDR3
  // channels calibrated (by the host here), led[2] yellow = the accelerator runs or halted cleanly
  assign led = {board_led[2] | board_led[1], pcie_link_up & (&calib), board_led[0]};
endmodule

