#!/usr/bin/env python3
"""Generate the MIG 7-series DDR3 configuration (.prj) and pin XDC for both YPCB-00338 channels.

Pin source: the board's DDR3 pin lists (bonetto-soc boards/ypcb-00338/constraints/ddr3_ch0.xdc,
ddr3_ch1.xdc, from TiferKing/ypcb_00338_1p1_hack MEMORY_CH*.ucf), copied into ../constraints
as ddr3_ch0.pins.xdc / ddr3_ch1.pins.xdc so the build does not depend on another checkout.

Memory: 9 x Micron MT41K256M8DA-125 per channel (x8, 2 Gb: 15 row, 10 column, 3 bank bits),
one rank, 72 data bits = 64 + an ECC byte, 2 GiB of data per channel. The board has NO DM pins,
so MIG runs with the data mask disabled and ECC enabled: partial AXI writes (the accelerator
writes single bytes and masked words) are then done by MIG as read-modify-write. Without ECC
MIG would ignore write strobes and corrupt neighbouring bytes.

  python3 gen_mig_prj.py [--check] [--speed 800|1066] [--no-ecc]

--check only prints the byte-group analysis (bank / byte group of every DQ, DQS pin; derived
from the xc7k480t-ffg1156 IOB site map in xc7k480t_ffg1156_iob.txt, extracted from the openXC7
chip database: bank = Y // 50, byte group = ((Y % 50) - 1) // 12).
"""
from __future__ import annotations

import argparse
import collections
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONS = HERE.parent / "constraints"
OUT = HERE.parent / "vivado" / "mig"

SPEEDS = {  # DDR3 data rate -> (tCK ps, MIG PHY input clock MHz)
    800: (2500, 200.0),     # 400 MHz CK, 4:1 -> ui_clk 100 MHz
    1066: (1875, 266.667),  # 533 MHz CK, 4:1 -> ui_clk 133 MHz (needs a 266.667 MHz input)
}


def site_map() -> dict:
    m = {}
    for line in (HERE / "xc7k480t_ffg1156_iob.txt").read_text().split("\n"):
        if line.strip():
            pin, site = line.split()
            x, y = re.match(r"IOB_X(\d+)Y(\d+)", site).groups()
            m[pin] = (int(x), int(y))
    return m


def read_pins(ch: int) -> dict:
    pins = {}
    for line in (CONS / f"ddr3_ch{ch}.pins.xdc").read_text().split("\n"):
        mm = re.search(r"PACKAGE_PIN (\w+) \[get_ports \{?([\w\[\]]+)\}?\]", line)
        if mm:
            name = mm[2].replace("ddr3_ch1_", "ddr3_")
            # MIG declares these one-rank signals as [0:0] vectors
            if name in ("ddr3_ck_p", "ddr3_ck_n", "ddr3_cke", "ddr3_cs_n", "ddr3_odt"):
                name += "[0]"
            pins[name] = mm[1]
    return pins


def analyze(ch: int, pins: dict, sites: dict) -> list[str]:
    def loc(p):
        x, y = sites[p]
        r = y % 50
        return (x, y // 50), r, None if r in (0, 49) else (r - 1) // 12
    issues, lines = [], []
    for k in range(9):
        dq = [pins[f"ddr3_dq[{8 * k + i}]"] for i in range(8)]
        groups = collections.Counter((loc(p)[0], loc(p)[2]) for p in dq)
        sp, sn = loc(pins[f"ddr3_dqs_p[{k}]"]), loc(pins[f"ddr3_dqs_n[{k}]"])
        same = len(groups) == 1 and (sp[0], sp[2]) in groups
        lines.append(f"  lane {k}: DQ in {dict(groups)}; DQS_P bank{sp[0]} row{sp[1]} group{sp[2]}"
                     f", DQS_N row{sn[1]}" + ("" if same else "   <-- DQS not in the DQ group"))
        if not same:
            issues.append(f"CH{ch} lane {k}: DQS and DQ byte groups differ")
    ctl = collections.Counter(loc(p)[0] for n, p in pins.items() if "dq" not in n)
    lines.append(f"  address/command banks (column, bank index): {dict(ctl)}")
    return lines + [f"  ISSUE: {i}" for i in issues]


def pin_xdc(ch: int, pins: dict) -> str:
    """The channel's pins under MIG's port names (for the GUI's 'Fixed Pin Out: Read XDC')."""
    out = [f"# YPCB-00338 DDR3 channel {ch} pins, MIG port names (generated by gen_mig_prj.py)"]
    for name, pad in sorted(pins.items()):
        out.append(f"set_property PACKAGE_PIN {pad} [get_ports {{{name}}}]")
    return "\n".join(out) + "\n"


def prj(ch: int, pins: dict, speed: int, ecc: bool) -> str:
    tck, fin = SPEEDS[speed]
    width = 72 if ecc else 64
    pin_lines = []
    for name, pad in sorted(pins.items()):
        if not ecc and re.match(r"ddr3_dq(s_[pn])?\[(\d+)\]", name):
            idx = int(re.search(r"\[(\d+)\]", name)[1])
            if (name.startswith("ddr3_dq[") and idx >= 64) or (name.startswith("ddr3_dqs") and idx >= 8):
                continue
        std = "DIFF_SSTL15" if name.startswith(("ddr3_ck_", "ddr3_dqs_")) else "SSTL15"
        pin_lines.append(f'      <Pin VCCAUX_IO="HIGH" IOSTANDARD="{std}" PADName="{pad}" '
                         f'SLEW="" name="{name}" IN_TERM="" />')
    pins_xml = "\n".join(pin_lines)
    return f"""<?xml version='1.0' encoding='UTF-8'?>
<!-- YPCB-00338 DDR3 channel {ch}: 9 x MT41K256M8DA-125, DDR3-{speed}, {width}-bit{' ECC' if ecc else ''}.
     Generated by boards/ypcb-00338/scripts/gen_mig_prj.py - see docs/board.md. -->
<Project NoOfControllers="1" >
    <ModuleName>mig_ddr3_ch{ch}</ModuleName>
    <dci_inouts_inputs>1</dci_inouts_inputs>
    <dci_inputs>1</dci_inputs>
    <Debug_En>OFF</Debug_En>
    <DataDepth_En>1024</DataDepth_En>
    <LowPower_En>ON</LowPower_En>
    <XADC_En>Disabled</XADC_En>
    <TargetFPGA>xc7k480t-ffg1156/-2</TargetFPGA>
    <Version>4.2</Version>
    <SystemClock>No Buffer</SystemClock>
    <ReferenceClock>No Buffer</ReferenceClock>
    <SysResetPolarity>ACTIVE LOW</SysResetPolarity>
    <BankSelectionFlag>FALSE</BankSelectionFlag>
    <InternalVref>{1 if speed <= 800 else 0}</InternalVref>
    <dci_hr_inouts_inputs>50 Ohms</dci_hr_inouts_inputs>
    <dci_cascade>0</dci_cascade>
    <Controller number="0" >
        <MemoryDevice>DDR3_SDRAM/Components/MT41K256M8XX-125</MemoryDevice>
        <TimePeriod>{tck}</TimePeriod>
        <VccAuxIO>1.8V</VccAuxIO>
        <PHYRatio>4:1</PHYRatio>
        <InputClkFreq>{fin:.3f}</InputClkFreq>
        <UIExtraClocks>0</UIExtraClocks>
        <MMCM_VCO>{int(round(1e6 / tck * 2))}</MMCM_VCO>
        <MMCMClkOut0> 1.000</MMCMClkOut0>
        <MMCMClkOut1>1</MMCMClkOut1>
        <MMCMClkOut2>1</MMCMClkOut2>
        <MMCMClkOut3>1</MMCMClkOut3>
        <MMCMClkOut4>1</MMCMClkOut4>
        <DataWidth>{width}</DataWidth>
        <DeepMemory>1</DeepMemory>
        <DataMask>0</DataMask>
        <ECC>{'Enabled' if ecc else 'Disabled'}</ECC>
        <Ordering>Normal</Ordering>
        <BankMachineCnt>4</BankMachineCnt>
        <CustomPart>FALSE</CustomPart>
        <NewPartName></NewPartName>
        <RowAddress>15</RowAddress>
        <ColAddress>10</ColAddress>
        <BankAddress>3</BankAddress>
        <MemoryVoltage>1.5V</MemoryVoltage>
        <C0_MEM_SIZE>{2 << 30 if ecc or width == 64 else 0}</C0_MEM_SIZE>
        <UserMemoryAddressMap>BANK_ROW_COLUMN</UserMemoryAddressMap>
        <PinSelection>
{pins_xml}
        </PinSelection>
        <System_Clock>
            <Pin PADName="No connect" Bank="Select Bank" name="sys_clk_i" />
        </System_Clock>
        <System_Control>
            <Pin PADName="No connect" Bank="Select Bank" name="sys_rst" />
            <Pin PADName="No connect" Bank="Select Bank" name="init_calib_complete" />
            <Pin PADName="No connect" Bank="Select Bank" name="tg_compare_error" />
        </System_Control>
        <TimingParameters>
            <Parameters twtr="7.5" trrd="6" trefi="7.8" tfaw="30" trtp="7.5" tcke="5" trfc="160" trp="13.75" tras="35" trcd="13.75" />
        </TimingParameters>
        <mrBurstLength name="Burst Length" >8 - Fixed</mrBurstLength>
        <mrBurstType name="Read Burst Type and Length" >Sequential</mrBurstType>
        <mrCasLatency name="CAS Latency" >{6 if speed == 800 else 7}</mrCasLatency>
        <mrMode name="Mode" >Normal</mrMode>
        <mrDllReset name="DLL Reset" >No</mrDllReset>
        <mrPdMode name="DLL control for precharge PD" >Slow Exit</mrPdMode>
        <emrDllEnable name="DLL Enable" >Enable</emrDllEnable>
        <emrOutputDriveStrength name="Output Driver Impedance Control" >RZQ/7</emrOutputDriveStrength>
        <emrMirrorSelection name="Address Mirroring" >Disable</emrMirrorSelection>
        <emrCSSelection name="Controller Chip Select Pin" >Enable</emrCSSelection>
        <emrRTT name="RTT (nominal) - On Die Termination (ODT)" >RZQ/6</emrRTT>
        <emrPosted name="Additive Latency (AL)" >0</emrPosted>
        <emrOCD name="Write Leveling Enable" >Disabled</emrOCD>
        <emrDQS name="TDQS enable" >Enabled</emrDQS>
        <emrRDQS name="Qoff" >Output Buffer Enabled</emrRDQS>
        <mr2PartialArraySelfRefresh name="Partial-Array Self Refresh" >Full Array</mr2PartialArraySelfRefresh>
        <mr2CasWriteLatency name="CAS write latency" >{5 if speed == 800 else 6}</mr2CasWriteLatency>
        <mr2AutoSelfRefresh name="Auto Self Refresh" >Enabled</mr2AutoSelfRefresh>
        <mr2SelfRefreshTempRange name="High Temparature Self Refresh Rate" >Normal</mr2SelfRefreshTempRange>
        <mr2RTTWR name="RTT_WR - Dynamic On Die Termination (ODT)" >Dynamic ODT off</mr2RTTWR>
        <PortInterface>AXI</PortInterface>
        <AXIParameters>
            <C0_C_RD_WR_ARB_ALGORITHM>RD_PRI_REG</C0_C_RD_WR_ARB_ALGORITHM>
            <C0_S_AXI_ADDR_WIDTH>31</C0_S_AXI_ADDR_WIDTH>
            <C0_S_AXI_DATA_WIDTH>512</C0_S_AXI_DATA_WIDTH>
            <C0_S_AXI_ID_WIDTH>4</C0_S_AXI_ID_WIDTH>
            <C0_S_AXI_SUPPORTS_NARROW_BURST>0</C0_S_AXI_SUPPORTS_NARROW_BURST>
        </AXIParameters>
    </Controller>
</Project>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--speed", type=int, default=800, choices=sorted(SPEEDS))
    ap.add_argument("--no-ecc", action="store_true",
                    help="64-bit without ECC: only safe if the board has DM pins (it does not)")
    a = ap.parse_args()
    sites = site_map()
    top = ["# DDR3 pin locations for otpu_fpga_top's ports (generated by gen_mig_prj.py).",
           "# Locations only: the MIG IP constrains I/O standards, VREF and termination; these",
           "# duplicate its locations under the top-level names so they bind either way."]
    for ch in (0, 1):
        for name, pad in sorted(read_pins(ch).items()):
            port = name.replace("ddr3_", f"DDR3_{ch}_")
            top.append(f"set_property PACKAGE_PIN {pad} [get_ports {{{port}}}]")
    if not a.check:
        (CONS / "otpu_ddr3_pins.xdc").write_text("\n".join(top) + "\n")
    for ch in (0, 1):
        pins = read_pins(ch)
        print(f"CH{ch}: {len(pins)} pins")
        for line in analyze(ch, pins, sites):
            print(line)
        if a.check:
            continue
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / f"mig_ddr3_ch{ch}.prj").write_text(prj(ch, pins, a.speed, not a.no_ecc))
        (OUT / f"mig_ddr3_ch{ch}_pins.xdc").write_text(pin_xdc(ch, pins))
        print(f"  wrote {OUT / f'mig_ddr3_ch{ch}.prj'}")


if __name__ == "__main__":
    main()
