#!/usr/bin/env python3
"""The calibration CPU's firmware (tools/litedram/calcpu.py, docs/litedram.md section 9): its
build configuration from a LiteDRAM build's csr.csv and sdram_init.py, the RV32I image for the
core's memory, and the same C built for this machine (the equivalence tests).

    python3 fw.py header BUILD_DIR OUT.h      # selfcal_cfg.h: CSR addresses per channel, the
                                              # init sequence, the PHY settings, test patterns
    python3 fw.py target BUILD_DIR OUT_DIR    # OUT_DIR/selfcal.bin (+ .elf, .map, .lst)
    python3 fw.py host BUILD_DIR OUT_DIR      # OUT_DIR/libselfcal.{so,dylib} (SELFCAL_HOST)

Stdlib only (no LiteX): the configuration comes from ddrcal (the same parsing of sdram_init.py
the host calibration uses). The selfcal CSRs come from csr.csv when it has them, else from their
fixed place (SELFCAL_BASE: calcpu.py pins the block at CSR location 16), so the tests can build
the firmware against the existing test images' maps.
"""
import argparse
import importlib.util
import math
import os
import random
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# ddrcal by its path: the package's __init__ wants numpy, which a LiteX environment may lack
_spec = importlib.util.spec_from_file_location("_selfcal_ddrcal",
                                               HERE.parents[2] / "opentpu" / "host" / "ddrcal.py")
ddrcal = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ddrcal)

SELFCAL_BASE = 0x8000                   # CSR location 16 x 0x800 (calcpu.py pins it)
SELFCAL_CSRS = ("hold", "config", "status", "state", "mbox_adr", "mbox_dat")   # in block order
MEM_BYTES = 16384                       # the firmware memory (calcpu.py's default)
RV_CC = os.environ.get("RV_CC", "riscv64-elf-gcc")
RV_FLAGS = ["-march=rv32i", "-mabi=ilp32", "-O2", "-ffreestanding", "-nostdlib",
            "-msmall-data-limit=0", "-fno-builtin", "-Wall", "-Wextra", "-Werror"]
SOURCES = ("cal.c",)


class _Regs:
    def __init__(self, regs):
        self.regs = regs


def config(build):
    """(regs, Dram) of a LiteDRAM build directory (csr.csv, sdram_init.py)."""
    build = Path(build)
    regs = ddrcal.csr_map(build / "csr.csv")
    for i, n in enumerate(SELFCAL_CSRS):
        regs.setdefault(f"selfcal_{n}", (SELFCAL_BASE + 4 * i, 1))
    return regs, ddrcal.Dram(_Regs(regs), build / "sdram_init.py")


def header(build):
    """selfcal_cfg.h for a build: everything the firmware takes from the build, as C."""
    regs, d = config(build)
    phy = d.phy
    nph, db, nm = phy["nphases"], phy["databits"], phy["modules"]
    assert (nph, db, nm, phy["delays"], phy["bitslips"]) == (4, 72, 9, 32, 8), \
        "the firmware is written for 4 phases, 72 bits (9 lanes), 32 taps, 8 bitslips"
    sys_hz = phy["sys_hz"]
    period = round(56 * phy["vco_hz"] / (4 * sys_hz))
    wl = phy.get("phy") == "wl"
    chans = [ch for ch in (0, 1) if ddrcal.Chan(_Regs(regs), ch).name("ddrphy_dly_sel") in regs]
    cyc = lambda s: int(math.ceil(s * sys_hz))

    def words(name, n=1):
        a, k = regs[name]
        assert k == n, f"{name}: {k} words, the firmware writes {n}"
        return a

    L = [f"/* Generated by tools/litedram/selfcal_fw/fw.py from {Path(build).name}: do not edit. */",
         "#include <stdint.h>",
         f"#define SYS_HZ {int(sys_hz)}u", f"#define NCH {len(chans)}", f"#define NM {nm}",
         f"#define NPH {nph}", f"#define NDELAYS {phy['delays']}", f"#define NBITSLIPS {phy['bitslips']}",
         f"#define RDPHASE {phy['rdphase']}", f"#define WRPHASE {phy['wrphase']}",
         f"#define PERIOD {period}", f"#define WRAP {period if wl else 0}",
         f"#define MIN_WINDOW {ddrcal.MIN_WINDOW}",
         f"#define N_SEEDS {len(ddrcal.SEEDS)}", "#define SCAN_SEEDS 1",
         "#define PAT_WORDS 5", f"#define WAIT_1MS {cyc(1e-3)}u", f"#define WAIT_1S {cyc(1.0)}u",
         f"#define WAIT_60S {cyc(60.0)}ull", "#define BIST_MIB 64",
         "#define BIST_SEED0 0x0123456789ABCDEFull",
         f"#define CSR_SELFCAL_CONFIG 0x{regs['selfcal_config'][0]:x}u",
         f"#define CSR_SELFCAL_STATE 0x{regs['selfcal_state'][0]:x}u",
         f"#define N_INIT {len(d.init_sequence)}", ""]
    assert ddrcal.SEEDS[0] == 42        # the scan's seeds, (42,): the first of SEEDS
    L += ["static const struct { uint32_t a, ba, cmd, wait, control; } INIT_SEQ[N_INIT] = {"]
    for comment, a, ba, cmd, delay, control in d.init_sequence:
        L.append(f"    {{{a}, {ba}, 0x{cmd:x}, {cyc(max(delay / sys_hz * 4, 20e-6))}u, {int(control)}}},"
                 f"  /* {comment} */")
    L += ["};", "", f"/* Dram.pattern(seed) for SEEDS {ddrcal.SEEDS}: per phase, most significant word first */",
          "static const uint32_t PAT[N_SEEDS][NPH][PAT_WORDS] = {"]
    for s in ddrcal.SEEDS:
        rng = random.Random(s)
        pats = [rng.getrandbits(2 * db) for _ in range(nph)]
        L.append("    {" + ", ".join("{" + ", ".join(f"0x{(p >> 32 * (4 - i)) & 0xFFFFFFFF:08x}u"
                                                    for i in range(5)) + "}" for p in pats) + "},")
    L += ["};", "", "struct ch_csr {",
          "    uint32_t rst, dly_sel, rdly_dq_rst, rdly_dq_inc, rdly_dq_bitslip_rst, rdly_dq_bitslip;",
          "    uint32_t wdly_dq_bitslip_rst, wdly_dq_bitslip, rdphase, wrphase, dly_sel_bits;",
          "    uint32_t dfii_control, pi_command[NPH], pi_command_issue[NPH], pi_address[NPH];",
          "    uint32_t pi_baddress[NPH], pi_wrdata[NPH], pi_rddata[NPH];",
          "    uint32_t bist_start, bist_mode, bist_base, bist_length, bist_seed, bist_done;",
          "    uint32_t bist_lane_errors[NM];",
          "    uint32_t dqs_shift, dqs_busy, dqs_steps;",
          "    uint32_t mmcm_reset, mmcm_locked, drp_adr, drp_dat_w, drp_dat_r, drp_read, drp_write,",
          "             drp_drdy;",
          "    uint32_t cal_ready;",
          "    uint8_t per_bit, has_bist, has_ready, wl_groups, groups[NM];",
          "};", "", "static const struct ch_csr CH[NCH] = {"]
    for ch in chans:
        c = ddrcal.Chan(_Regs(regs), ch)
        has = lambda n: c.name(n) in regs
        a = lambda n, k=1: f"0x{words(c.name(n), k):x}u" if has(n) else "0xFFFFFFFFu"
        per = lambda fmt, k=1: "{" + ", ".join(a(fmt.format(p), k) for p in range(nph)) + "}"
        groups = phy.get("groups", {}).get(str(ch))
        wl_groups = bool(wl and groups)
        if wl_groups:
            assert all(has(n) for n in ("wclk_mmcm_reset", "wclk_drp_adr")), "WL image without wclk"
        L += ["    {",
              "        " + ", ".join(a("ddrphy_" + n) for n in (
                  "rst", "dly_sel", "rdly_dq_rst", "rdly_dq_inc", "rdly_dq_bitslip_rst",
                  "rdly_dq_bitslip", "wdly_dq_bitslip_rst", "wdly_dq_bitslip", "rdphase", "wrphase",
                  "dly_sel_bits")) + ",",
              f"        {a('sdram_dfii_control')}, {per('sdram_dfii_pi{}_command')},",
              f"        {per('sdram_dfii_pi{}_command_issue')}, {per('sdram_dfii_pi{}_address')},",
              f"        {per('sdram_dfii_pi{}_baddress')}, {per('sdram_dfii_pi{}_wrdata', 5)},",
              f"        {per('sdram_dfii_pi{}_rddata', 5)},",
              "        " + ", ".join(a("bist_" + n) for n in ("start", "mode", "base", "length"))
              + f", {a('bist_seed', 2)}, {a('bist_done')},",
              "        {" + ", ".join(a(f"bist_lane{m}_errors") for m in range(nm)) + "},",
              "        " + ", ".join(a("phase_dqs_" + n) for n in ("shift", "busy", "steps")) + ",",
              "        " + ", ".join(a("wclk_" + n) for n in (
                  "mmcm_reset", "mmcm_locked", "drp_adr", "drp_dat_w", "drp_dat_r", "drp_read",
                  "drp_write", "drp_drdy")) + ",",
              f"        {a('cal_ready')},",
              f"        {int(has('ddrphy_dly_sel_bits'))}, {int(has('bist_start'))}, "
              f"{int(has('cal_ready'))}, {int(wl_groups)},",
              "        {" + ", ".join(str(g) for g in (groups or [0] * nm)) + "},",
              "    },"]
    L += ["};", ""]
    return "\n".join(L)


def write_header(build, out):
    Path(out).write_text(header(build))


def _run(cmd, **kw):
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if r.returncode:
        raise RuntimeError(f"{' '.join(map(str, cmd))}\n{r.stdout}{r.stderr}")
    return r


def target(build, out, fw_id=0, mem_bytes=MEM_BYTES, cc=RV_CC):
    """The RV32I image (VexRiscv minimal: no M, no C): out/selfcal.bin, loaded at 0 and run from
    there; returns its bytes. No initialised writable data (the CPU restarts in place when the
    host releases it)."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    write_header(build, out / "selfcal_cfg.h")
    objcopy = cc.replace("gcc", "objcopy")
    objdump = cc.replace("gcc", "objdump")
    elf = out / "selfcal.elf"
    _run([cc, *RV_FLAGS, f"-DFW_ID=0x{fw_id:x}u", f"-DMEM_BYTES={mem_bytes}", f"-I{out}", f"-I{HERE}",
          "-T", str(HERE / "link.ld"), f"-Wl,--defsym=MEM_BYTES={mem_bytes}", "-Wl,--no-relax",
          f"-Wl,-Map={out / 'selfcal.map'}", "-o", str(elf), str(HERE / "crt0.S"),
          *[str(HERE / s) for s in SOURCES], str(HERE / "main.c"), "-lgcc"])
    _run([objcopy, "-O", "binary", str(elf), str(out / "selfcal.bin")])
    (out / "selfcal.lst").write_text(_run([objdump, "-d", str(elf)]).stdout)
    data = (out / "selfcal.bin").read_bytes()
    return data


def words(data, mem_bytes=MEM_BYTES):
    """The image as the memory's 32-bit words (little-endian), zero-filled to its size."""
    assert len(data) <= mem_bytes, f"firmware {len(data)} bytes > memory {mem_bytes}"
    data = data + bytes(-len(data) % 4)
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)] + \
        [0] * ((mem_bytes - len(data)) // 4)


def host(build, out, cc=None):
    """The firmware for this machine (SELFCAL_HOST: every access a callback), a shared library
    for ctypes: selfcal_host_setup(rd, wr, mbox), selfcal_run(mask, stride)."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    write_header(build, out / "selfcal_cfg.h")
    cc = cc or os.environ.get("CC") or shutil.which("cc") or "cc"
    lib = out / ("libselfcal.dylib" if sys.platform == "darwin" else "libselfcal.so")
    _run([cc, "-O2", "-shared", "-fPIC", "-DSELFCAL_HOST", "-Wall", "-Wextra", "-Werror",
          f"-I{out}", f"-I{HERE}", "-o", str(lib), *[str(HERE / s) for s in SOURCES],
          str(HERE / "host.c")])
    return lib


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("what", choices=["header", "target", "host"])
    ap.add_argument("build", help="LiteDRAM build directory (csr.csv, sdram_init.py)")
    ap.add_argument("out")
    a = ap.parse_args()
    if a.what == "header":
        write_header(a.build, a.out)
    elif a.what == "target":
        data = target(a.build, a.out)
        print(f"{len(data)} bytes")
    else:
        print(host(a.build, a.out))


if __name__ == "__main__":
    main()
